models/Mensajero.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "mensajero".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $cedula
 * @property string $telefono
 * @property string $direccion
 * @property string $placa
 * @property string $anho
 * @property integer $id_modelo_id
 * @property string $user
 *
 * @property Modelo $idModelo
 */
class Mensajero extends \yii\db\ActiveRecord
{
    public $marca;
        /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mensajero';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'user', 'correo'], 'required'],
            [['id_modelo_id', 'marca'], 'integer'],
            [['nombre', 'user'], 'string', 'max' => 200],
            [['correo'],'email'],
            [['cedula', 'placa', 'anho'], 'string', 'max' => 20],
            [['telefono'], 'string', 'max' => 40],
            [['direccion'], 'string', 'max' => 450],
            [['id_modelo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Modelo::className(), 'targetAttribute' => ['id_modelo_id' => 'id_modelo']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'cedula' => 'Cédula',
            'telefono' => 'Teléfono',
            'direccion' => 'Dirección',
            'correo' => 'Correo',
            'placa' => 'Placa',
            'anho' => 'Año',
            'id_modelo_id' => 'Id Modelo ID',
            'user' => 'Usuario',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdModelo()
    {
        return $this->hasOne(Modelo::className(), ['id_modelo' => 'id_modelo_id']);
    }
}

controllers/MensajeroController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Mensajero;
use app\models\MensajerosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\UserSearch;
use app\models\AuthAssignment;
use app\models\User;
use dektrium\user\helpers\Password;
use app\models\Modelo;
/**
 * MensajeroController implements the CRUD actions for Mensajero model.
 */
class MensajeroController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Mensajero models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MensajerosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Mensajero model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Mensajero model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
//print_r($_POST);
        //die();
        $model = new Mensajero();

        $usuario = new UserSearch();
        $rol = new AuthAssignment();


        $length = 10;
        $chars = array_merge(range(0,9), range('a','z'), range('A','Z'));
        shuffle($chars);
        $password = implode(array_slice($chars, 0, $length));

        if ($model->load(Yii::$app->request->post())) {
            if(!$model->save()) {
                print_r($model->getErrors());
                die();
            }
                $usuario->username = $model->user;
                $usuario->email=$model->correo;
                $usuario->password_hash = Password::hash($password);
                $usuario->auth_key=0;
                $usuario->created_at=0;
                $usuario->updated_at=0;
                $usuario->flags=0;
                $usuario->cargo_gerencial=0;
                $usuario->cargo=0;
                $usuario->id_mensajero = $model->id;
                $usuario->confirmed_at = 1491044212;
                $usuario->save(false);

                $rol->item_name = 'reparto';
                $rol->user_id = $usuario->id;
                $rol->save(false);

                $correo_envio = $model->correo;
                $login =  $usuario->username;

                    if(!$this->notificacion($model,$password, $usuario)){
                        \Yii::$app->getSession()->setFlash('error', '¡Error en el envío de notificación!');
                    }

            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }

         public function notificacion($model,$password, $usuario)
    {
      $envio = 0;
        $mensaje_sup ='  <p>'.$model->nombre.', <br>
                        Km100 le informa que ha sido registrado como Representante de Reparto, sus datos son:
                    </p>
                    <p>
                        <strong>Nombre de Usuario: </strong>'.$usuario->username.'<br>
                        <strong>Clave de Acceso: </strong>'.$password.'<br>
                    </p>
        ';
        if (!Yii::$app->mailer->compose(['html'=>'layout'], ['content'=> $mensaje_sup])
                        ->setFrom([Yii::$app->params['adminEmail'] => 'KM100'])
                        ->setTo($model->correo)
                        ->setSubject('Notificación de Registro')
                        ->send())
        {
            $envio=0;

        }
     
      if ($envio==0){
            return true;
        }else{
            return false;
        }
    }

    /**
     * Updates an existing Mensajero model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Mensajero model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Mensajero model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Mensajero the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Mensajero::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/mensajero/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Marca;
use app\models\Modelo;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Mensajero */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="mensajero-form">

    <?php $form = ActiveForm::begin(); ?>


            <div class="row">
   
        <div class="col-md-4">
            <?= $form->field($model, 'nombre')->textInput(['maxlength' => true])->label('NOMBRE <span class="obligatorio">*&nbsp;</span>');  ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'cedula')->textInput(['maxlength' => true])->label('CÉDULA ');  ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'telefono')->textInput(['maxlength' => true])->label('TELÉFONO');  ?>
        </div>
    </div>
    <div class="row">
           <div class="col-md-3">
            <?= $form->field($model, 'correo')->textInput(['maxlength' => true])->label('CORREO DE USUARIO<span class="obligatorio">*&nbsp;</span>');  ?>
        </div>
       <div class="col-md-3">
            <?= $form->field($model, 'user')->textInput(['maxlength' => true])->label('NOMBRE DE USUARIO<span class="obligatorio">*&nbsp;</span>');  ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'direccion')->textInput(['maxlength' => true])->label('DIRECCIÓN'); ?>
        </div>
    </div>
    <br>
    <div class="row" style="border-bottom: 1px solid #222d32;">
        <h4>ASOCIACIÓN DE VEHÍCULO</h4>
    </div>
    <br>
      <div class="row">
   
        <div class="col-md-3">
            <?= $form->field($model, 'placa')->textInput(['maxlength' => true])->label('PLACA ');  ?>
        </div>

            <div class="col-md-3">
                <?php 
                    $marcas = ArrayHelper::map(Marca::find()->orderBy('nombre')->all(), 'id_marca', 'nombre');
                    if(!$model->isNewRecord){
                        $model->marca = $model->idModelo->id_marca;
                    }
                    echo $form->field($model, "marca")->dropDownList(
                        $marcas,
                        [
                            'prompt'=>'Selecciona la marca',
                            'class' => 'form-control',
                            'onchange'=>'
                            var ident = $(this).attr("id");
                            var nom = ident.split("-");
                            $.get( "'.Url::toRoute('caso/listarmodelos').'", { id: $(this).val() } )
                                .done(function( data ) {
                                    $( "#nmodelo" ).html( data );
                                }
                            );                                              ',
                        ] )->label('MARCA'); 
                ?>
            </div>
            <div class="col-md-3">                                                         
            <?php
                $modelos=array(); //echo "trae: {$i} --- ";
                if(!$model->isNewRecord){
                    $modelos = ArrayHelper::map(Modelo::find()->where(['id_marca'=>$model->idModelo->id_marca])->orderBy('nombre')->all(), 'id_modelo', 'nombre');
                }
                echo $form->field($model, "id_modelo_id")->dropDownList(
                $modelos,
                    [
                    'prompt'=>'Selecciona el modelo',
                    'class' => 'form-control',
                    'id'    => 'nmodelo' ]
                )->label('MODELO');
                    ?>
            </div>



          <div class="col-md-3">

                                               <?php 
                          $anhos = ['1980'=>'1980', '1981'=>'1981','1982'=>'1982','1983'=>'1983',
                                                     '1984'=>'1984', '1985'=>'1985','1986'=>'1986','1987'=>'1987',
                                                     '1988'=>'1988', '1989'=>'1989','1990'=>'1990','1991'=>'1991',
                                                     '1992'=>'1992', '1993'=>'1993','1994'=>'1994','1995'=>'1995',
                                                     '1996'=>'1996', '1997'=>'1997','1998'=>'1998','1999'=>'1999',
                                                     '2000'=>'2000', '2001'=>'2001','2002'=>'2002','2003'=>'2003',
                                                     '2004'=>'2004', '2005'=>'2005','2006'=>'2006','2007'=>'2007',
                                                     '2008'=>'2008', '2009'=>'2009','2010'=>'2010','2011'=>'2011',
                                                     '2012'=>'2012', '2013'=>'2013','2014'=>'2014','2015'=>'2015',
                                                     '2016'=>'2016', '2017'=>'2017','2018'=>'2018','2019'=>'2019',
                                                      
                                                    ];
                                    echo $form->field($model, 'anho')->dropDownList(
                                            $anhos,
                                            [
                                                'prompt'=>'Seleccione...',
                                                'class' => 'form-control',
                                            ] );
                               

                                    ?>

                                    </div>  
    </div>

<br><br><br>

 <?php
      if(!$model->isNewRecord){
      ?>
          <div class="row" align="center">
              <div>
                  <?= Html::a('CANCELAR', ['index'], ['class' => 'btn btn-cancelar']) ?>
                  &nbsp;&nbsp;&nbsp;
                  <?= Html::submitButton('GUARDAR CAMBIOS', ['class' => 'btn btn-primario']) ?>
              </div>
          </div>
      <?php
      }else{
      ?>
          <div class="form-group" align="center">
              <?= Html::submitButton('GUARDAR', ['class' => 'btn btn-primario']) ?>
          </div>
      <?php
      }
  ?>
 

    <?php ActiveForm::end(); ?>

</div>

views/mensajero/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\MensajerosSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="mensajero-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nombre') ?>

    <?= $form->field($model, 'cedula') ?>

    <?= $form->field($model, 'telefono') ?>

    <?= $form->field($model, 'direccion') ?>

    <?php // echo $form->field($model, 'placa') ?>

    <?php // echo $form->field($model, 'anho') ?>

    <?php // echo $form->field($model, 'id_modelo_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/mensajero/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Mensajero */

$this->title = 'REGISTRO DE REPRESENTANTE DE REPARTO';
?>
<div class="mensajero-create">

    <div class="row">
        <div class="col-md-1 col-xs-3">
            <h4 class="titulo"><img src="<?= Yii::$app->request->baseUrl ?>/img/driver_64.png" alt=""></h4>
        </div>
        <div class="col-md-10 col-xs-9" style="padding-top: 20px;">
            <h4 class="titulo"><span> <?= Html::encode( $this->title ) ?></span></h4>
        </div>
    </div>
    </br>
    <div class="row" style="border-bottom: 1px solid #222d32;">
          <div class="col-xs-12 col-md-6">
              <h4>DATOS DEL REPRESENTANTE DE REPARTO</h4>
          </div>
          <div class="col-xs-12 col-md-6">
            <div align="right">
                  <?php
                  echo Html::a('Listado de Representantes de Reparto', ['index'], ['class' => 'btn btn-small-gris']);
                  ?>
            </div>
          </div>
      </div>
      <br>

    <?= $this->render('_form', [
        'model' => $model
    ]) ?>

</div>
 

views/mensajero/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use app\models\Modelo;
use app\models\Marca;

/* @var $this yii\web\View */
/* @var $searchModel app\models\MensajerosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


$this->title = 'LISTADO DE REPRESENTANTE DE REPARTO';

?>
<div class="mensajero-index">

    <div class="row">
        <div class="col-md-1 col-xs-3">
            <h4 class="titulo"><img src="<?= Yii::$app->request->baseUrl ?>/img/driver_64.png" alt=""></h4>
        </div>
        <div class="col-md-10 col-xs-9" style="padding-top: 20px;">
            <h4 class="titulo"><span> <?= Html::encode( $this->title ) ?></span></h4>
        </div>
    </div>
    </br>

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right">
                <?= Html::a('Registrar Representante de Reparto',['mensajero/create'], ['class' => 'btn btn-small-gris']) ?>   
            </div>
        </div>
        </br>
        </br>
    </div>

    <div class= "row">
        <div class="col-md-12">
            <?= GridView::widget([
                 'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'summary' => '',
                 'options' =>[
                                'class' => 'grid',
                            ],
                'columns' => [
                    [
                        'attribute' => 'nombre',
                        'enableSorting' => false,
                    ],
                    [
                        'attribute' => 'cedula',
                        'enableSorting' => false,
                    ],
                    [
                        'attribute' => 'telefono',
                        'enableSorting' => false,
                    ],
                    [
                        'attribute' => 'direccion',
                        'enableSorting' => false,
                    ],
                    [
                        'attribute' => 'placa',
                        'enableSorting' => false,
                    ],
                    [
                        'attribute' => 'id_modelo_id',
                        'label' => 'Marca',
                        'format' => 'html',
                        'value' => function ($model) {

         
                               
                                         return ($model->idModelo) ? $model->idModelo->idMarca->nombre.' -> '.$model->idModelo->nombre: "-";
                        },

                             'filter' => Select2::widget([
                            'name' => 'MensajerosSearch[id_marca]',
                            // 'data' => ArrayHelper::map(Marca::find()->joinWith('Modelo')->orderBy('nombre')->all(), 'id_marca', 'nombre'),
                            'data' => ArrayHelper::map(Marca::find()->orderBy('nombre')->all(), 'id_marca', 'nombre'),
                            'hideSearch' => true,
                            'options' => ['placeholder' => 'Marcas',],
                            'pluginOptions' => [
                                'allowClear' => true
                            ],
                        ]),
                        'enableSorting' => false,
                    ],
                    //'anho',
                                          
                 [  
                                    'class' => 'yii\grid\ActionColumn',
                                    //'contentOptions' => ['style' => 'width:260px;'],
                                    'header'=>'Acciones',
                                    'template' => '{menu}',
                                    'buttons' => [

                                        //view button
                                        'menu' => function ($url, $model) {

                                             return  '<div class="dropdown">
                                                      <button class="btn btn-default dropdown-toggle btn-sm" type="button" data-toggle="dropdown"><i class="fa fa-cog" aria-hidden="true"></i>
                                                      <span class="caret"></span></button>
                                                      <ul class="dropdown-menu">
                                                        
                                                        <li>'.Html::a('<span><i class="fa fa-pencil fa-sm" aria-hidden="true"></i></span> Modificar Datos',[ '/mensajero/update', 'id' => $model->id ]).' </li>
                                                        
                                                      </ul>
                                                    </div>';


                                        },
                                    ],

                               ],


          
                ],
            ]); ?>
        </div>
      </div>
 
</div>

 

views/mensajero/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Mensajero */
$this->title = 'MODIFICAR REPRESENTANTE DE REPARTO';
?>
<div class="mensajero-update">

 	<div class="row">
        <div class="col-md-1 col-xs-3">
            <h4 class="titulo"><img src="<?= Yii::$app->request->baseUrl ?>/img/driver_64.png" alt=""></h4>
        </div>
        <div class="col-md-10 col-xs-9" style="padding-top: 20px;">
            <h4 class="titulo"><span> <?= Html::encode( $this->title ) ?></span></h4>
        </div>
    </div>
    </br>
    <div class="row" style="border-bottom: 1px solid #222d32;">
            <div class="col-xs-12 col-md-4">
                <h4>DATOS DEL REPRESENTANTE DE REPARTO</h4>
            </div>
            <div class="col-xs-12 col-md-8">
              <div align="right">
                    <?php
                    echo Html::a('Listado de Representantes de Reparto', ['index'], ['class' => 'btn btn-small-gris']);
                    ?>&nbsp;&nbsp;&nbsp;<?php
                    //Lllamar a la accion anterior!!!!!!
                    echo Html::a('Registrar Nuevo Representante de Reparto', ['create'], ['class' => 'btn btn-small-gris']);
                    ?>
              </div>
            </div>
        </div>
        <br>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>


 

views/mensajero/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Mensajero */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Mensajeros', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="mensajero-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nombre',
            'cedula',
            'telefono',
            'direccion',
            'placa',
            'anho',
            'id_modelo_id',
        ],
    ]) ?>

</div>