models/SolicitudCompraEstacion.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "solicitud_compra_estacion".
 *
 * @property integer $id
 * @property integer $tipo_solicitud
 * @property integer $id_estacion
 * @property string $ficha
 * @property string $placa
 * @property integer $id_modelo
 * @property string $fecha_registro
 * @property integer $id_vehiculo
 *
 * @property Estacion $idEstacion
 * @property Modelo $idModelo
 * @property Vehiculo $idVehiculo
 * @property SolicitudPiezaEstacion[] $solicitudPiezaEstacions
 */
class SolicitudCompraEstacion extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'solicitud_compra_estacion';
    }

    public $id_marca, $id_modelo2;
    /**
     * @inheritdoc
     */
    public function rules()
    {//'ficha' 'id_modelo', 'placa'
        return [
 
            // [['tipo_solicitud', 'id_estacion', 'id_modelo', 'id_vehiculo', 'id_caso'], 'integer'],
 
            // [['tipo_solicitud', 'id_estacion', ], 'required'],
 
            [['tipo_solicitud', 'id_estacion', 'id_modelo', 'id_vehiculo', 'id_marca', 'id_modelo2', 'id_caso'], 'integer'],
            [['tipo_solicitud', 'id_estacion'], 'required'],
 
            [['fecha_registro'], 'safe'],
            [['ficha', 'placa'], 'string', 'max' => 20],
            [['id_estacion'], 'exist', 'skipOnError' => true, 'targetClass' => Estacion::className(), 'targetAttribute' => ['id_estacion' => 'id_estacion']],
            [['id_modelo'], 'exist', 'skipOnError' => true, 'targetClass' => Modelo::className(), 'targetAttribute' => ['id_modelo' => 'id_modelo']],
            [['id_vehiculo'], 'exist', 'skipOnError' => true, 'targetClass' => Vehiculo::className(), 'targetAttribute' => ['id_vehiculo' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tipo_solicitud' => 'Tipo Solicitud',
            'id_estacion' => 'Id Estacion',
            'ficha' => 'Ficha',
            'placa' => 'Placa',
            'id_modelo' => 'Id Modelo',
            'fecha_registro' => 'Fecha Registro',
            'id_vehiculo' => 'Id Vehiculo',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdEstacion()
    {
        return $this->hasOne(Estacion::className(), ['id_estacion' => 'id_estacion']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdModelo()
    {
        return $this->hasOne(Modelo::className(), ['id_modelo' => 'id_modelo']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdVehiculo()
    {
        return $this->hasOne(Vehiculo::className(), ['id' => 'id_vehiculo']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSolicitudPiezaEstacions()
    {
        return $this->hasMany(SolicitudPiezaEstacion::className(), ['id_solicitud_compra_estacion' => 'id']);
    }
}

controllers/SolicitudCompraEstacionController.php
<?php

namespace app\controllers;

use Yii;
use app\models\SolicitudCompraEstacion;
use app\models\SolicitudCompraEstacionSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Vehiculo;
use app\models\Pieza;
use app\models\Estacion;
use app\models\Proveedor;
use app\models\SolicitudPiezaEstacion;
use app\models\SolicitudCompraPieza;
use app\models\EstadoCompraPieza;
use app\models\PipelineCompraPieza;
use app\models\SolicitudCompraPiezaSearch;
use app\models\User;
use app\models\SolicitudCompraProveedorSearch;
use app\models\CotizacionProveedor;
use app\models\CotizacionProveedorPieza;
use app\models\CotizacionProveedorPiezaSearch;
use yii\helpers\ArrayHelper;
use app\models\OrdenCompraPieza;
use app\models\OrdenCompraPiezaSearch;
use app\models\OrdenCompraFactura;
use app\models\SolicitudCompraProveedor;
use app\models\DespachoSearch;
use app\models\Despacho;
use app\models\DespachoProveedorPieza;
use app\models\DespachoProveedorPiezaSearch;
use yii\db\Query;
use kartik\mpdf\Pdf;
use mPDF;
use yii\helpers\Json;
use app\models\Caso;
use app\models\CasoPiezaEstacion;
use app\models\EstacionUsuario;



/**
 * SolicitudCompraEstacionController implements the CRUD actions for SolicitudCompraEstacion model.
 */
class SolicitudCompraEstacionController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all SolicitudCompraEstacion models.
     * @return mixed
     */
    public function actionIndex()
    {

        Yii::$app->user->identity->id;
        
        $searchModel = new SolicitudCompraPiezaSearch();
        $dataProvider = $searchModel->searchEstacion(Yii::$app->request->queryParams);
        $dataProvider->query->orderBy('id ASC');

        // Proveedor recomendado en base a la cantidad de ordenes de compras
        // $mejor_proveedor = OrdenCompraPieza::find()
        // ->select(['proveedor.nombre as pro, id_proveedor, COUNT(id_proveedor) totales'])
        // ->leftJoin('proveedor', '`proveedor`.`id` = `orden_compra_pieza`.`id_proveedor`')
        // ->groupBy(['id_proveedor'])
        // ->orderBy('totales DESC')
        // ->limit(3)
        // ->all();

        //Proveedor recomendado en base al porcentaje de descuento
        $mejor_proveedor = Proveedor::find()
        ->orderBy('porcentaje DESC')
        ->limit(5)
        ->all();
        

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'mejor_proveedor' => $mejor_proveedor,
        ]);
    }

    /**
     * Displays a single SolicitudCompraEstacion model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionListar($id)
    {        
       $countpieza = Pieza::find()
       ->where(['tipo_pieza_id' => $id])
       ->count();

       $pieza = Pieza::find()
       ->where(['tipo_pieza_id' => $id])
       ->all();

       if($countpieza>0){
            echo "<option value=''> Seleccione... </option>";
            foreach($pieza as $pieza){
                echo "<option value='".$pieza->id_pieza."'>".$pieza->nombre."</option>";
            }
        }
        else{
            echo "<option>-</option>";
        }
    }

    /**
     * Creates a new SolicitudCompraEstacion model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($type = 0)
    {
        // print_r(Yii::$app->request->post());
        // die();
        $model = new SolicitudCompraEstacion();
        $model_cotizacion_estacion_pieza = [new SolicitudPiezaEstacion];

        $cliente = (\Yii::$app->user->can('estaciones todas') )?'':EstacionUsuario::find()->where(['user_id'=>Yii::$app->user->identity->ID ])->one()->estacion->idEmpresa->cliente;
        $empresa = (\Yii::$app->user->can('estaciones todas'))?'':EstacionUsuario::find()->where(['user_id'=>Yii::$app->user->identity->ID ])->one()->estacion->idEmpresa;
        $estaciones = (\Yii::$app->user->can('estaciones asociadas'))?ArrayHelper::getColumn(EstacionUsuario::find()->select('estacion_id')->where(['user_id'=>Yii::$app->user->identity->ID ])->asArray()->all(), 'estacion_id'):'';
        
        //Consultando los vehiculos a los cuales se les puede registraruna solicitud de compra
        if ( \Yii::$app->user->can('estaciones todas') ) {
            //Se muestran todos los vehiculos que no esten en transito
            $vehiculos = ArrayHelper::map(Vehiculo::find()->select(['mva'])->where(['transito' => 0])->distinct()->all(), 'mva', 'mva');
        } else if ( \Yii::$app->user->can('estaciones cliente') ){
            //Busco las estaciones asociadas al cliente del usuario
            $v_estaciones = Estacion::find()->joinWith('idEmpresa')->where([ 'empresa.cliente_id' => $cliente ])->all();
            $ids_estaciones = ArrayHelper::getColumn($v_estaciones, 'id_estacion');
            $vehiculos = ArrayHelper::map(Vehiculo::find()->select(['mva'])->join('INNER JOIN', 'flota', 'flota.id_vehiculo = vehiculo.id')->where(['vehiculo.transito' => 0, 'flota.id_estacion' => $ids_estaciones])->andWhere('flota.fecha_fin IS NULL')->distinct()->all(), 'mva', 'mva');
        } else if( \Yii::$app->user->can('estaciones asociadas') ) {
            //Busco las estaciones asociadas al usuario
            $v_estaciones = EstacionUsuario::find()->where(['user_id'=>Yii::$app->user->identity->ID ])->all();
            $ids_estaciones = ArrayHelper::getColumn($v_estaciones, 'estacion_id');
            $vehiculos = ArrayHelper::map(Vehiculo::find()->select(['mva'])->join('INNER JOIN', 'flota', 'flota.id_vehiculo = vehiculo.id')->where(['vehiculo.transito' => 0, 'flota.id_estacion' => $ids_estaciones])->andWhere('flota.fecha_fin IS NULL')->distinct()->all(), 'mva', 'mva');
        }

        if ($model->load(Yii::$app->request->post())) {
            
            $band1 = $model->tipo_solicitud;

            if ( $band1 == 1 ) {
                $model->placa = Vehiculo::findOne($model->placa)->placa;
                $model->id_modelo = $model->id_modelo2;
            } else if( $band1 == 2 ) {
                $model->id_modelo = $model->id_modelo;
            } else if( $band1 == 3 ) {
                $model->id_modelo = NULL;
            } else if( $band1 == 4 ) {               
                $model->placa = Vehiculo::findOne($model->placa)->placa;
                $model->id_modelo = $model->id_modelo2;
                if( Yii::$app->request->post('name') == 1) {
                    $model->id_caso = $model->id_caso;
                }
            }

            $model->fecha_registro = date('Y-m-d');
            if($model->save()) {
                // caso
                if($band1 == 4 && !empty($_POST['SolicitudCompraEstacion']['id_caso'])) {
                    $model_caso_pieza = new CasoPiezaEstacion();
                    $model_caso_pieza->id_solicitud_compra_estacion = $model->id;
                    $model_caso_pieza->id_caso = $_POST['SolicitudCompraEstacion']['id_caso'];
                    $model_caso_pieza->save();
                }
                //die('entra2');
                $this->estacionPiezas($model->id);

                $band = true;
                if($band) {                    
                    //Se crea la Solicitud de compra de pieza
                    $model_solicitud_compra_pieza = new SolicitudCompraPieza();
                    $model_solicitud_compra_pieza->fecha = date("Y-m-d H:i:s");
                    $model_solicitud_compra_pieza->codigo_estado = 0; //Asignado
                    $model_solicitud_compra_pieza->id_solicitud_compra_estacion = $model->id;
                    $model_solicitud_compra_pieza->origen_solicitud = 2;// para saber que la solicitud es de estacion
                    if($band1 == 4 && !empty($_POST['SolicitudCompraEstacion']['id_caso'])) {
                        $model_solicitud_compra_pieza->id_caso_estacion = $_POST['SolicitudCompraEstacion']['id_caso'];// para saber que la solicitud es de estacion
                    }


                    if ($model_solicitud_compra_pieza->save()) {
                        //Se cambia el estado de la solicitud en el pipeline de compra de pieza
                        $estado_compra_pieza = EstadoCompraPieza::findOne(['codigo' => 0])->id; //Asignado
                        $model_pipeline_compra_pieza = new PipelineCompraPieza();
                        $model_pipeline_compra_pieza->fecha = date('Y-m-d');
                        $model_pipeline_compra_pieza->id_solicitud_compra_pieza = $model_solicitud_compra_pieza->id;
                        $model_pipeline_compra_pieza->id_estado_compra_pieza = $estado_compra_pieza;
                        $model_pipeline_compra_pieza->save();
                        unset($model_pipeline_compra_pieza);

                        
                        if($band1 == 10) {
                            $model_solicitud_compra_pieza->aprobacion = 2;
                            $model_solicitud_compra_pieza->codigo_estado = 3;
                            $model_solicitud_compra_pieza->update();
                            $model_solicitud_compra_proveedor = new SolicitudCompraProveedor();
                            //$model_proveedor = Proveedor::findOne($proveedor); // buscar el id del proveedor en licitaciones
                            $model_proveedor_id = 7;
                            $model_proveedor_porcentaje = 10;
                            $costo_licitacion = 222;

views/solicitud-compra-estacion/checklist-recepcion.php
<?php 
use yii\helpers\Html;
use kartik\form\ActiveForm;
use kartik\grid\GridView;

$this->title = 'CHECKLIST DE RECEPCIÓN DE PIEZAS';
?>
<div class="checklist-recepcion">
	<div class="row">
		<div class="col-md-1 col-xs-3">
			<h4 class="titulo"><img src="<?= Yii::$app->request->baseUrl ?>/img/list_64.png" alt=""></h4>
		</div>
		<div class="col-md-10 col-xs-9" style="padding-top: 30px;">
			<h4 class="titulo"><span> <?= Html::encode( $this->title ) ?></span></h4>
		</div>
	</div>
	</br>
	<?php $form = ActiveForm::begin(); ?>

	<div class="row">
        <div class="col-md-4 col-xs-12">
            <div class="pull-rigth" style="margin-top: 30px;">
                <?= Html::a('Listado de solicitudes',[ '/solicitud-compra-estacion/index' ], ['class' => 'btn btn-small-gris']) ?> 
            </div>
        </div>
        <div class="col-md-4 col-md-offset-4 col-xs-12">
        	<?= $form->field($model_orden_compra, 'id')->textInput(['disabled' => true, ])->label('NÚMERO DE ORDEN DE COMPRA') ?>
        </div>
        </br>
    </div>

    <?php 
        if($model_solicitud_compra_estacion->id_vehiculo != null):        
    ?>
    <div class="row">
        <div class="col-xs-12">
            <p class="titulo-form">DATOS DEL VEHÍCULO</p>
            <hr>
        </div>
    </div>


    <div class="row">

        <div class="col-md-4 col-xs-12">
            <?= $form->field($model_vehiculo, 'id_modelo')->textInput(['disabled' => true, 'value' => $model_vehiculo->idModelo->idMarca->nombre ])->label('Marca') ?>
        </div>

        <div class="col-md-4 col-xs-12">
            <?= $form->field($model_vehiculo, 'id_modelo')->textInput(['value' => strtoupper($model_vehiculo->idModelo->nombre), 'disabled' => true])->label('Modelo') ?>
        </div>

        <div class="col-md-4 col-xs-12">
            <?= $form->field($model_vehiculo, 'chasis')->textInput(['maxlength' => true, 'disabled' => true]) ?>
        </div>

    </div>
    <?php else: ?>
    
    <div class="row">
        <div class="col-xs-12">
            <p class="titulo-form">DATOS DEL MODELO DE VEHÍCULO</p>
            <hr>
        </div>
    </div>

    <div class="row">
        <?php if($model_solicitud_compra_estacion->tipo_solicitud != 3){ ?>
        <div class="col-md-4 col-xs-12">
            <?= $form->field($model_solicitud_compra_estacion, 'id_modelo')->textInput(['disabled' => true, 'value' => $model_solicitud_compra_estacion->idModelo->idMarca->nombre ])->label('Marca') ?>
        </div>
        <div class="col-md-4 col-xs-12">
            <?= $form->field($model_solicitud_compra_estacion, 'id_modelo')->textInput(['disabled' => true, 'value' => $model_solicitud_compra_estacion->idModelo->nombre ])->label('Modelo') ?>
        </div>
        
        <?php }else{ ?>
            <div class="col-xs-12">
                <h4>Aplica para todos los modelos (Misceláneos)</h4>
            </div>
        <?php } ?>
    </div>

    <?php endif ?>
    </br>

    <div class="row">
        <div class="col-xs-12">
            <p class="titulo-form">DATOS DEL PROVEEDOR</p>
            <hr>
        </div>
    </div>


    <div class="row">
		
		<div class="col-md-4 col-xs-12">
            <?= $form->field($model_proveedor, 'nombre')->textInput(['maxlength' => true, 'disabled' => true])->label('NOMBRE DEL PROVEEDOR') ?>
        </div>

        <div class="col-md-4 col-xs-12">
            <?= $form->field($model_proveedor, 'identificacion')->textInput(['maxlength' => true, 'disabled' => true])->label('RNC') ?>
        </div>

        <div class="col-md-4 col-xs-12">
            <?= $form->field($model_proveedor, 'telefono')->textInput(['maxlength' => true, 'disabled' => true])->label('TELÉFONO') ?>
        </div>

        <div class="col-md-8 col-xs-12">
            <?= $form->field($model_proveedor, 'direccion')->textInput(['maxlength' => true, 'disabled' => true])->label('DIRECCIÓN') ?>
        </div>

        <div class="col-md-4 col-xs-12">
            <?= $form->field($model_proveedor, 'nombre_representante')->textInput(['maxlength' => true, 'disabled' => true])->label('CONTACTO') ?>
        </div>
    </div>
    <br>

    <div class="row">
        <div class="col-xs-12">
            <p class="titulo-form">PIEZAS RECIBIDAS</p>
            <hr>
        </div>
    </div>

    <div class="row">
    	<div class="col-xs-12">
    		<?= GridView::widget([
                'dataProvider' => $dataProvider,
                'summary' => '',
                'id' =>'cotizacion-pieza-grid',
                'tableOptions' => ['class' => 'table table-responsive', 'id' =>'cotizacion-pieza-table'],
                'options' =>[
                    'class' => 'grid-blue',
                ],
                'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],
                'columns' => [
                   [
                   		'attribute' => 'idSolicitudPiezaEstacion.idPieza.tipoPieza.nombre',
                        'label' => 'Tipo',
                        'format' => 'text',
                        'enableSorting' => false,
                        'contentOptions'=>['style'=>'text-align:left;'],
                    ],
                    [
                        'attribute' => 'idSolicitudPiezaEstacion.idPieza.nombre',
                        'label' => 'Descripcion',
                        'format' => 'text',
                        'enableSorting' => false,
                        'contentOptions'=>['style'=>'text-align:left;'],
                    ],
         
                            [
                        'attribute' => 'serial',
                        'label' => 'Serial',
                        'format' => 'raw',
                        'filter' => false,
                        'enableSorting' => false,
                        'value' => function( $model ){
                            return Html::textInput('serial[]', $model->serial,['class' => 'form-control', 'type' => 'text', 'style' => 'text-align:center; font-size: 10pt; float: left;', 'required' => true ]);
                        },
                        'contentOptions'=>['style'=>'text-align: center;'],
                        'headerOptions' => ['width' => '150',],
                    ],
                    [
                        'attribute' => 'cantidad_comprar',
                        'label' => 'Cantidad',
                        'format' => 'text',
                        'enableSorting' => false,
                        'contentOptions'=>['style'=>'text-align:center;'],
                    ],
                    [
                        'attribute' => 'costo',
                        'label' => 'Costo',
                        'format' => 'text',
                        'enableSorting' => false,
                        'contentOptions'=>['style'=>'text-align:right;'],
                        'value' => function( $model ){
                            return number_format(floatval($model->costo), 2, ',', '.').' RD$';
                        },
                    ],
                    [
                    	'attribute' => 'cantidad_recibida',
                        'label' => 'Cantidad recibida',
                        'format' => 'raw',
                        'filter' => false,
                        'enableSorting' => false,
                        'value' => function( $model ){
                            return Html::textInput('recibido[]', $model->cantidad_recibida,['class' => 'form-control', 'type' => 'text', 'style' => 'text-align:center; font-size: 10pt; float: left;', 'required' => true ]).
                            Html::hiddenInput('pieza_id[]', $model->id, ['class' => 'pieza_id', 'readonly' => true ]);;
                        },
                        'contentOptions'=>['style'=>'text-align: center;'],
                        'headerOptions' => ['width' => '150',],
                    ],
                ],
            ]); ?>
    	</div>
    </div>
	<br>
	<br>
    <div class="row">
        <div class="col-xs-12 col-md-12">
            <?= $form->field($model_orden_compra, 'observacion_recepcion')->textarea(['rows' => 3])->label('OBSERVACIONES') ?>
        </div>
    </div>
    </br>
    </br>
    </br>
    </br>
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="form-group text-center">
                <?= Html::submitButton('ACEPTAR', ['class' => 'btn btn-submit']) ?>
            </div>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/solicitud-compra-estacion/despacho.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use app\models\DespachoProveedorPieza;

$this->title = 'DESPACHAR PIEZAS';
?>

<div class="despacho">
	<div class="row">
		<div class="col-md-1 col-xs-3">
			<h4 class="titulo"><i class="fa fa-truck fa-4x" aria-hidden="true"></i></h4>
		</div>
		<div class="col-md-10 col-xs-9" style="padding-top: 20px;">
			<h4 class="titulo"><span> <?= Html::encode( $this->title ) ?></span></h4>
		</div>
	</div>
    </br>
    </br>
    <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
                <div class="pull-left">
                    <?php // Html::a('+ Nuevo Envío', '#', ['class' => 'btn btn-small-gris', 'data' => ['toggle' => 'modal', 'target' => '#alertAddEnvioBodegaModal']]) ?>
                    <?= Html::a('Listado de solicitudes', ['solicitud-compra-estacion/index', 'id' => $model->id ], ['class' => 'btn btn-small-gris',]) ?>
                </div>
                <div class="pull-right">
                    <?php // Html::a('+ Nuevo Envío', '#', ['class' => 'btn btn-small-gris', 'data' => ['toggle' => 'modal', 'target' => '#alertAddEnvioBodegaModal']]) ?>
                    <?= ($cantidad_piezas != $cantidad_piezas_despacho)? Html::a('+ Nuevo Envío', ['solicitud-compra-estacion/crearenvio', 'id' => $model->id ], ['class' => 'btn btn-small-verde',]): '' ?>
                </div>
        </div>
    </div>
    <div class="clearfix"></div>
    </br>
    <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'tableOptions' => ['class' => 'table table-responsive'],
                'summary' => '',
                'options' =>[
                    'class' => 'grid',
                ],
                'columns' => [
                    [
                        'attribute' => 'numero',
                        'label' => 'No. Envío',
                        'format' => 'text',
                        'contentOptions'=>['style'=>'text-align:center;'],
                        'filter' => false,
                        'enableSorting' => false,
                    ],
                    [
                        'attribute' => 'estado',
                        'label' => 'Estatus',
                        'format' => 'text',
                        'value' => function ($model) {
                            if ($model->estado == 0) {
                                return 'EN PROCESO';
                            } elseif ($model->estado == 1){
                                return 'ENVIADO A MENSAJERO';
                            } elseif ($model->estado == 2){
                                return 'RECIBIDA POR MENSAJERO';
                            } else {
                                return 'ENTREGADA';
                            }
                        },
                        'contentOptions'=>['style'=>'text-align:center;'],
                        'filter' => false,
                        'enableSorting' => false,
                    ],
                    [
                        'attribute' => 'fecha',
                        'label' => 'Fecha de Envío',
                        'format' => 'text',
                        'value' => function($model){
                            if ( $model->fecha )
                                return date( 'd/m/Y', strtotime($model->fecha) );
                            else
                                return '-';
                        },
                        'contentOptions'=>['style'=>'text-align:center;'],
                        'enableSorting' => false,
                    ],
                    [
                        'label' => 'No. de Piezas',
                        'format' => 'text',
                        'value' => function($model){
                            $cant = count(DespachoProveedorPieza::find()->where(['id_despacho' => $model->id])->all());
                            return $cant;
                        },
                        'contentOptions'=>['style'=>'text-align:center;'],
                        //'headerOptions' => ['width' => '300',],
                    ],
                    [
                        'attribute' => 'traslado',
                        'label' => 'Traslado',
                        'format' => 'text',
                        'value' => function($model){
                            if ( $model->traslado )
                                return $model->traslado;
                            else
                                return '-';
                        },
                        'contentOptions'=>['style'=>'text-align:center;'],
                        'enableSorting' => false,
                    ],
                    [
                        'attribute' => 'idMensajero.nombre',
                        'label' => 'Representante de Reparto',
                        'format' => 'text',
                        'value' => function($model){
                            if ( $model->id_mensajero )
                                return $model->idMensajero->nombre;
                            else
                                return '-';
                        },
                        'contentOptions'=>['style'=>'text-align:center;'],
                        'enableSorting' => false,
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'header' => 'Acciones',
                        'template' => '{update}',
                        'buttons' => [
                            'update' => function ($url, $model) {
                                return ($model->estado == 0 )?Html::a('<i class="fa fa-pencil" aria-hidden="true"></i>', ['/solicitud-compra-estacion/despachopiezas', 'id' => $model->id], ['title' => 'Editar Envío', ]):Html::a('<i class="fa fa-file" aria-hidden="true"></i>', ['/solicitud-compra-estacion/imprimirtranslado', 'id' => $model->id], ['title' => 'PDF Envío', ]);;
                            },
                        ],
                        'contentOptions'=>['style'=>'text-align:center;'],
                    ],
                ],
            ]); ?>
        </div>
    </div>
</div>

<script>
    $('.table').removeClass( "table-bordered table-striped" );
</script>