controllers/ServicioController.php
<?php

namespace app\controllers;

use Yii;
use yii\helpers\Json;
use yii\helpers\BaseFileHelper;
use yii\helpers\ArrayHelper;
use yii\db\Query;
use app\models\Servicio;
use app\models\ServicioSearch;
use app\models\Vehiculo;
use app\models\EstadoVehiculo;
use app\models\Estado;
use app\models\VehiculoSearch;
use app\models\Marca;
use app\models\Modelo;
use app\models\Caso;
use app\models\CasoServicio;
use app\models\ServicioTaller;
use app\models\PipelineServicio;
use app\models\EstadoServicio;
use app\models\Empresa;
use app\models\ServicioVehiculoEscaneadoSearch;
use app\models\ServicioVehiculoEscaneado;
use app\models\CasoServicioSearch;
use app\models\TallerSearch;
use app\models\Taller;
use app\models\User;
use app\models\Pieza;
use app\models\SolicitudServicioTaller;
use app\models\SolicitudServicioTallerSearch;
use app\models\CotizacionTaller;
use app\models\CotizacionTallerSearch;
use app\models\CotizacionTallerAnalista;
use app\models\CotizacionTallerPieza;
use app\models\CotizacionTallerPiezaSearch;
use app\models\CotizacionTallerActividad;
use app\models\CotizacionTallerActividadSearch;
use app\models\UploadCotizacionTaller;
use app\models\OrdenTrabajo;
use app\models\OrdenTrabajoSearch;
use app\models\OrdenCompraPiezaSearch;
use app\models\SolicitudCompraPieza;
use app\models\EstadoCompraPieza;
use app\models\PipelineCompraPieza;
use yii\web\UploadedFile;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\UploadActaPolicial;
use app\models\UploadReporteAccidente;
use app\models\ChecklistAvaluo;
use app\models\Variable;
use app\models\ServicioEncuesta;
use app\models\ChecklistAvaluoPieza;
use app\models\ChecklistavaluoPiezasSearch;
use app\models\PiezaServicioTaller;
use app\models\GarantiaVehiculoSearch;
use app\models\GarantiaVehiculo;
use app\models\ServicioMensaje;
use app\models\EstacionUsuario;
use kartik\mpdf\Pdf;

/**
 * ServicioController implements the CRUD actions for Servicio model.
 */
class ServicioController extends Controller
{
    /**
     * @inheritdoc
     */
    public $basePath ='./uploads/servicios/';

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Servicio models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ServicioSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->orderBy('id DESC');

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Servicio model.
     * @param integer $id, $origen //$origen Saber de dónde vengo (Listado de solicitudes o Gestión de servicios)
     * @return mixed
     */
    public function actionView($id, $origen )
    {
        $model = $this->findModel($id);
        $model_vehiculo = Vehiculo::findOne([ 'id' => $model->id_vehiculo ]);
        
        $searchModel_caso = new CasoServicioSearch([ 'id_servicio' => $model->id ]);
        $dataProvider_caso = $searchModel_caso->search(Yii::$app->request->queryParams);
        
        return $this->render('view', [
            'model' => $model,
            'model_vehiculo' => $model_vehiculo,
            'dataProvider_caso' => $dataProvider_caso,
            'origen' => $origen
        ]);
    }

    /**
     * Creates a new Servicio model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Servicio();
        $model_caso = new Caso();
        $acta = new UploadActaPolicial();
        $reporte = new UploadReporteAccidente();

        $cliente = (\Yii::$app->user->can('registro servicio todos') )?'':EstacionUsuario::find()->where(['user_id'=>Yii::$app->user->identity->ID ])->one()->estacion->idEmpresa->cliente;
        $empresa = (\Yii::$app->user->can('registro servicio todos'))?'':EstacionUsuario::find()->where(['user_id'=>Yii::$app->user->identity->ID ])->one()->estacion->idEmpresa;
        $estaciones = (\Yii::$app->user->can('registro servicio estaciones asociadas'))?ArrayHelper::getColumn(EstacionUsuario::find()->select('estacion_id')->where(['user_id'=>Yii::$app->user->identity->ID ])->asArray()->all(), 'estacion_id'):'';

        if ( \Yii::$app->user->can('registro servicio todos') ) {
            $vehiculos = ArrayHelper::map(Caso::find()->select(['ficha'])->distinct()->all(), 'ficha', 'ficha');
        } else if ( \Yii::$app->user->can('registro servicio cliente') ) {
            $v_estaciones = Estacion::find()->joinWith('idEmpresa')->where([ 'empresa.cliente_id' => $cliente ])->all();
            $ids_estaciones = ArrayHelper::getColumn($v_estaciones, 'id_estacion');
            $vehiculos = ArrayHelper::map(Caso::find()->select(['ficha'])->where(['id_estacion' => $ids_estaciones ])->distinct()->all(), 'ficha', 'ficha');
        } else if ( \Yii::$app->user->can('registro servicio estaciones asociadas') ) {
            $v_estaciones = EstacionUsuario::find()->where(['user_id'=>Yii::$app->user->identity->ID ])->all();
            $ids_estaciones = ArrayHelper::getColumn($v_estaciones, 'estacion_id');
            $vehiculos = ArrayHelper::map(Caso::find()->select(['ficha'])->where(['id_estacion' => $ids_estaciones ])->distinct()->all(), 'ficha', 'ficha');
        }
        if ( $model->load(Yii::$app->request->post()) ) {
            $servicios ="";

            if ( Yii::$app->request->post('tipo_servicio') ) {
                $checkboxes = Yii::$app->request->post('tipo_servicio');
                foreach($checkboxes as $c)
                    $servicios = $servicios .'*'.$c;  
            } else{
                \Yii::$app->getSession()->setFlash('error', 'Debe seleccionar los Servicios a Solicitar!');
                return $this->render('create', [
                    'model' => $model,
                    'model_caso' => $model_caso,
                ]);
            }

            $model->servicio = $servicios;
            $model->fecha = date('Y-m-d');
            $model->decision = 0;
            $model->linea = 0;
            $model->img_reporte = '';
            $model->aprobacion_estacion = -1;
            $model->registrado_por = Yii::$app->user->identity->id;

            if ( $model->save() ) {
                $path = $this->basePath . $model->id . '/';
                if ( !is_dir($path) ) {
                    mkdir( $path, 0777, true );
                }

                $casos = Yii::$app->request->post('Caso');

                //Guardar reporte
                $reporte->imageFiles = UploadedFile::getInstances($reporte, 'imageFiles');
                $reporte->upload($model->id);

                //Guardar acta policial
                $acta->imageFiles = UploadedFile::getInstances($acta, 'imageFiles');
                $acta->upload($model->id);

                $id_casos = '';
                foreach ($casos['id_caso'] as $key => $caso) {
                    $model_caso_servicio = new CasoServicio();
                    $model_caso_servicio->isNewRecord = true;
                    $model_caso_servicio->id_servicio = $model->id;
                    $model_caso_servicio->id_caso = $caso;
                    $model_caso_servicio->save();
                    unset($model_caso_servicio);
                    $id_casos = $id_casos.$caso.' ';
                }

                /* Pipeline -> Estado inicial Asignación */
                $estado_0 = EstadoServicio::findOne(['codigo' => 11])->id;
                $model_pipeline = new PipelineServicio();
                $model_pipeline->fecha = $model->fecha = date('Y-m-d');
                $model_pipeline->id_servicio = $model->id;
                $model_pipeline->id_estado_servicio = $estado_0;
                $model_pipeline->save();
                unset($model_pipeline);

            }else {
                print_r($model->getErrors());
                die();
            }

            $model_vehiculo = Vehiculo::findOne($model->id_vehiculo);

            try {
                //Email a quien registro la solicitud
                $mensaje_sup ='  <p>'.Yii::$app->user->identity->username.', <br>
                        Km100 le informa que la Solicitud de Servicio ha sido creada con éxito:
                        </p>
                        <p>
                            <strong>Nº Solicitud: </strong>'.$model->id.'<br>
                            <strong>MVA Ficha: </strong>'.$model_vehiculo->mva.'<br>
                            <strong>Nº Placa: </strong>'.$model_vehiculo->placa.'<br>
                            <strong>KM: </strong>'.$model_vehiculo->km.'<br>
                            <strong>Casos asociados: </strong>'.$id_casos.'<br>
                        </p>
                ';
                Yii::$app->mailer->compose(['html'=>'layout'], ['content'=> $mensaje_sup])
                    ->setFrom([Yii::$app->params['adminEmail'] => 'KM100'])
                    ->setTo(Yii::$app->user->identity->email)
                    ->setSubject('Registro de Solicitud de Servicio')
                    ->send();

                //Email al Planner
                $planners = User::find()->joinWith('authAssignments')->andWhere('auth_assignment.item_name = "planner"')->all();
                
                foreach ($planners as $user) {
                    $correos[] = $user->email;
                }

                $mensaje_sup ='  <p> Km100 le informa que una nueva Solicitud de Servicio ha sido registrada: </p>
                        <p>
                            <strong>Nº Solicitud: </strong>'.$model->id.'<br>

views/servicio/_pdf-orden-trabajo.php
<?php 

use yii\helpers\Html;

$subtotal = 0;
?>
<div class="content">
	Hola Mundo!!!!!!!!!!
</div>

views/servicio/checkin-taller.php
<?php 
use yii\helpers\Html;
use kartik\grid\GridView;
use kartik\form\ActiveForm;
use yii\db\Query;

$this->title = 'REGISTRAR CHECK-IN';
$servicios = explode("*", $model->servicio);

foreach ($servicios as $key => $servicio) {
    switch ($servicio) {
        case '0':
            $vector_servicios[] = 'Mecánica Ligera';
            break;

        case '1':
            $vector_servicios[] = 'Mecánica Especializada';
            break;

        case '2':
            $vector_servicios[] = 'Aire Acondicionado';
            break;

        case '3':
            $vector_servicios[] = 'Desabolladura y pintura';
            break;

        case '4':
            $vector_servicios[] = 'Accesorios';
            break;
        
        default:
            # code...
            break;
    }
    
}

$respuesta_servicios = implode(' / ', $vector_servicios);

$query = new query();
$query->select('es.nombre, es.color, es.codigo')
    ->from('pipeline_servicio p')
    ->join('INNER JOIN','estado_servicio es','es.id = p.id_estado_servicio')
    ->where('p.id_servicio = '. $model->id )
    ->orderBy('p.id desc');

$sql = $query->prepare(Yii::$app->db->queryBuilder)->createCommand()->rawSql;
$estado = Yii::$app->db->createCommand($sql)->queryOne();

?>

<div class="checkin-taller">

    <div class="row">
        <div class="col-md-1 col-xs-3">
            <h4 class="titulo"><i class="fa fa-qrcode fa-4x" aria-hidden="true"></i></h4>
        </div>
        <div class="col-md-10 col-xs-9" style="padding-top: 10px;">
            <h4 class="titulo"><span> <?= Html::encode( $this->title ) ?> </br> NÚMERO DE SOLICITUD <?= $model->id ?></span></h4>
        </div>
    </div>
    </br>

    <div class="row">
        <div class="col-md-3 col-xs-12">
            <p style="font-size: 11pt;"><b><?= Html::encode( 'ESCANEAR VEHÍCULO' ) ?></b></p>
            <?= Html::input('text', '', '', ['id' => 'codigo-vehiculo', 'class'=> 'form-control', 'placeholder' => 'Placa',] ) ?>
        </div>
        <div class="col-md-3 col-xs-12">
            <p style="font-size: 11pt;"><b><?= Html::encode( 'ESTATUS DE LA SOLICITUD' ) ?></b></p>
            <h4 style="margin-top: 15px;"><span class="label label-oval" style="background-color: <?= $estado['color'] ?>; text-transform: uppercase;">
                <?= $estado['nombre'] ?>
            </span></h4>
        </div>
    </div>
    </br>

    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-xs-12">
            <div class="pull-right">
                <?= Html::a('Listado de solicitudes',['/servicio/indextaller'], ['class' => 'btn btn-small-gris']) ?>
            </div>
        </div>
        </br>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <p class="titulo-form">DATOS DEL VEHÍCULO</p>
            <hr>
        </div>
    </div>


    <div class="row">

        <div class="col-md-4 col-xs-12">
            <?= $form->field($model_vehiculo, 'id_modelo')->textInput(['disabled' => true, 'value' => $model_vehiculo->idModelo->idMarca->nombre ])->label('Marca') ?>
        </div>

        <div class="col-md-4 col-xs-12">
            <?= $form->field($model_vehiculo, 'id_modelo')->textInput(['value' => strtoupper($model_vehiculo->idModelo->nombre), 'disabled' => true])->label('Modelo') ?>
        </div>

        <div class="col-md-4 col-xs-12">
            <?= $form->field($model_vehiculo, 'mva')->textInput(['maxlength' => true, 'disabled' => true])->label('Ficha o MVA') ?>
        </div>

        <div class="col-md-4 col-xs-12">
            <?= $form->field($model_vehiculo, 'chasis')->textInput(['maxlength' => true, 'disabled' => true]) ?>
        </div>

        <div class="col-md-4 col-xs-12">
            <?= $form->field($model_vehiculo, 'placa')->textInput(['maxlength' => true, 'disabled' => true]) ?>
        </div>

        <div class="col-md-4 col-xs-12">
            <?= $form->field($model_vehiculo, 'km')->textInput(['maxlength' => true, 'disabled' => true, 'value' => number_format(floatval($model_vehiculo->km), 0, ',', '.'). ' Km', ])->label('Km Actual') ?>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-xs-12">
            <p class="titulo-form">DATOS DE LA SOLICITUD</p>
            <hr>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-4 col-xs-12">
            <?= $form->field($model, 'id')->textInput(['maxlength' => true, 'disabled' => true,])->label('NÚMERO DE SOLICITUD') ?>
        </div>
        <div class="col-md-4 col-xs-12">
            <?= $form->field($model, 'servicio')->textInput(['maxlength' => true, 'disabled' => true, 'value' => $respuesta_servicios ])->label('TIPO DE SOLICITUD') ?>
        </div>
        <div class="col-md-4 col-xs-12">
            <div class="form-group">
                <?= Html::label('GARANTÍA DE CONCESIONARIO', '', ['class' => 'control-label']) ?>
                <?= Html::textInput('', 'No',['class' => 'form-control', 'disabled' => true,]) ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-4 col-xs-12">
            <div class="form-group">
                <?= Html::label('CLIENTE', '', ['class' => 'control-label']) ?>
                <?= Html::textInput('', $model->idEstacionActual->idEmpresa->nombre,['class' => 'form-control', 'disabled' => true,]) ?>
            </div>
        </div>
        <div class="col-md-4 col-xs-12">
            <?= $form->field($model, 'id_estacion_actual')->textInput(['maxlength' => true, 'disabled' => true, 'value' => $model->idEstacionActual->nombre])->label('ESTACIÓN') ?>
        </div>
        <div class="col-md-4 col-xs-12">
            <?= $form->field($model, 'linea')->textInput(['maxlength' => true, 'disabled' => true, 'value' => ($model->linea == 0)?'Quick Line':'Normal Line',])->label('LÍNEA') ?>
        </div>
    </div>
    </br>

    <?php ActiveForm::end(); ?>

</div>

<style>
	#codigo-vehiculo{
		font-size: 10pt;
		text-align: center;
		background-color: #fff2cc;
		border: none;
		color: black;
	}
</style>

<script>
	$('#codigo-vehiculo').on('keyup', function(event) {
        if ( event.keyCode == 13 ) {
            //event.stopImmediatePropagation();
            var input = $(this);
            var codigo = input.val();
            var id_servicio = <?= $model->id ?>;

            $.ajax({
                url: '../escanearvehiculotaller',
                type: 'post',
                data: {
                    codigo: codigo,
                    id_servicio: id_servicio,
                },
                success: function (response) {
                    event.preventDefault();

                    if ( response == 1 ) {
                    	location.reload();
                    } else if ( response == 0 ) {
                    	console.log('No se encuentra en estado de checkin');
                    } else if ( response == 2 ){
                        console.log('El codigo del vehiculo no coincide con la solicitud');
                    } else if ( response == 3 ) {
                        console.log('El codigo del vehiculo es incorrecto');
                    } else{
                        console.log('Otro error');
                    }

                    input.val('');
                    input.focus();
                }
            });
        }
    });
    $('#codigo-vehiculo').focus();
</script>

views/servicio/index-record.php
<?php

use yii\helpers\Html;
use yii\db\Query;
use kartik\grid\GridView;
use app\models\PipelineServicio;
use app\models\Empresa;
use app\models\CotizacionTallerActividadSearch;
use yii\helpers\ArrayHelper;
use app\models\Estacion;
use app\models\EstadoServicio;
use app\models\Modelo;
use app\models\Cliente;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ServicioSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'HISTORIAL DE SOLICITUDES';
?>
<div class="servicio-index">

    <div class="row">
        <div class="col-md-1 col-xs-3">
            <i class="fa fa-list-ul fa-3x" aria-hidden="true"></i>
        </div>
        <div class="col-md-10 col-xs-9">
            <h4 class="titulo"><span> <?= Html::encode( $this->title ) ?></span></h4>
        </div>
    </div>
    </br>
    </br>

    <div class="row">
        <div class="col-md-12 col-xs-12">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel'   => $searchModel,
                'tableOptions' => ['class' => 'table table-responsive', 'id' => 'grid-preventivos',],
                'summary' => '',
                'options' =>[
                    'class' => 'grid',
                ],
                'resizableColumns' => false,
                'pjax' => true,
                'columns' => [
                    [
                        'class'=>'kartik\grid\ExpandRowColumn',
                        'width'=>'50px',
                        'allowBatchToggle' => false,
                        'expandIcon' => '<i class="fa fa-caret-right" aria-hidden="true" style="color:#d9d9d9;"></i>',
                        'collapseIcon' => '<i class="fa fa-caret-down" aria-hidden="true" style="color:#d9d9d9;"></i>',
                        'value'=>function ($model, $key, $index, $column) {
                            $query = new query();
                            $query->select('es.nombre, es.color, es.codigo')
                                ->from('pipeline_servicio p')
                                ->join('INNER JOIN','estado_servicio es','es.id = p.id_estado_servicio')
                                ->where('p.id_servicio = '. $model->id )
                                ->orderBy('p.id desc');

                            $sql = $query->prepare(Yii::$app->db->queryBuilder)->createCommand()->rawSql;
                            $estado = Yii::$app->db->createCommand($sql)->queryOne();

                            if ( $estado['codigo'] == 10 || $estado['codigo'] == 11 ) {
                                return '<i></i>';
                            } else {
                                return GridView::ROW_COLLAPSED;
                            }
                        },
                        'detail'=>function ($model, $key, $index, $column) {
                            $pipeline_servicio = PipelineServicio::find()->where([ 'id_servicio' => $model->id ])->andWhere('id_estado_servicio != 10 AND id_estado_servicio != 11')->orderby('id DESC')->all();
                            $pipeline_servicio_first = PipelineServicio::find()->where([ 'id_servicio' => $model->id ])->orderby('id DESC')->one();
                            
                            if ( $pipeline_servicio_first->idEstadoServicio->codigo != 10 || $pipeline_servicio_first->idEstadoServicio->codigo != 11 ) {
                                if ( $pipeline_servicio_first->idEstadoServicio->codigo >= 5 && $pipeline_servicio_first->idEstadoServicio->codigo <= 9 ) {
                                    $query = new query();
                                    $query->select('c.id')
                                        ->from('solicitud_servicio_taller sst')
                                        ->join('INNER JOIN','cotizacion_taller c','c.id_solicitud_servicio_taller = sst.id AND c.estado = 1 AND c.activo = 1')
                                        ->where('sst.id_servicio = '. $model->id)
                                        ->orderBy('c.id desc');

                                    $sql = $query->prepare(Yii::$app->db->queryBuilder)->createCommand()->rawSql;
                                    $id_cotizacion = Yii::$app->db->createCommand($sql)->queryOne();

                                    $searchModel_cotizacion_actividad = new CotizacionTallerActividadSearch([ 'id_cotizacion_taller' => $id_cotizacion['id'] ]);
                                    $dataProvider_cotizacion_actividad = $searchModel_cotizacion_actividad->search(Yii::$app->request->queryParams);

                                    return Yii::$app->controller->renderPartial('_expand-solicitud-servicio', ['pipeline_servicio' => $pipeline_servicio, 'type' => 0, 'dataProvider_cotizacion_actividad' => $dataProvider_cotizacion_actividad, ]);
                                } else {
                                    return Yii::$app->controller->renderPartial('_expand-solicitud-servicio', ['pipeline_servicio' => $pipeline_servicio, 'type' => 0 ]);
                                }
                            } else{
                               return '';
                            }
                        },
                        'headerOptions'=>['class'=>'kartik-sheet-style'],
                        'expandOneOnly'=>true,
                        'enableRowClick' => true,
                    ],
                    [
                        'attribute' => 'id',
                        'label' => 'Número de solicitud',
                        'format' => 'text',
                        'filter' => true,
                        'enableSorting' => false,
                    ],
                    [
                        'attribute' => 'ficha',
                        'label' => 'MVA',
                        'format' => 'text',
                        'filter' => true,
                        'enableSorting' => true,
                    ],
                    [
                        'attribute' => 'id_modelo',
                        'label' => 'Modelo',
                        'format' => 'raw',
                        'filter' => true,
                        'enableSorting' => false,
                        'value' => function ($model, $key, $index, $column) {
                            return $model->idVehiculo->idModelo->nombre;
                        },
                        'filterType'=> GridView::FILTER_SELECT2,
                        'filter'=> ArrayHelper::map(Modelo::find()->orderBy('nombre')->all(), 'id_modelo', 'nombre'),
                        'filterWidgetOptions'=>[
                            'pluginOptions'=>['allowClear'=>true],
                        ],
                        'filterInputOptions'=>['placeholder'=>'Selecciona'],    
                    ],
                    [
                        'attribute' => 'servicio',
                        'label' => 'Tipo de solicitud',
                        'format' => 'raw',
                        'filterType'=> GridView::FILTER_SELECT2,
                        'filter'=> ['0'=>'Mecánica Ligera','1'=>'Mecánica Especializada','2'=>'Aire Acondicionado','3'=>'Desabolladura y pintura','4'=>'Accesorios'],
                        'filterWidgetOptions'=>[
                            'pluginOptions'=>['allowClear'=>true],
                        ],
                        'filterInputOptions'=>['placeholder'=>'Selecciona'],
                        'format'=>'raw',                   
                        'enableSorting' => false,
                        'value' => function( $model ){
                            if ( $model->servicio ) {
                                $servicios = explode("*", $model->servicio);

                                foreach ($servicios as $key => $servicio) {
                                    switch ($servicio) {
                                        case '0':
                                            $vector_servicios[] = 'Mecánica Ligera';
                                            break;

                                        case '1':
                                            $vector_servicios[] = 'Mecánica Especializada';
                                            break;

                                        case '2':
                                            $vector_servicios[] = 'Aire Acondicionado';
                                            break;

                                        case '3':
                                            $vector_servicios[] = 'Desabolladura y pintura';
                                            break;

                                        case '4':
                                            $vector_servicios[] = 'Accesorios';
                                            break;
                                        
                                        default:
                                            # code...
                                            break;
                                    }
                                    
                                }

                                $respuesta_servicios = implode('<br>', $vector_servicios);

                                return $respuesta_servicios;
                            } else{
                                return '-';
                            }
                        }
                    ],
                    [
                        'attribute' => 'id_company',
                        'label' => 'Empresa',
                        'format' => 'raw',
                        'filter' => true,
                        'enableSorting' => false,
                        'value' => function ($model, $key, $index, $column) {
                          return $model->idEstacionActual->idEmpresa->nombre;
                              },
                        'filterType'=> GridView::FILTER_SELECT2,
                        'filter'=> ArrayHelper::map(Empresa::find()->orderBy('nombre')->all(), 'id_empresa', 'nombre'),
                        'filterWidgetOptions'=>[
                            'pluginOptions'=>['allowClear'=>true],
                        ],
                        'filterInputOptions'=>['placeholder'=>'Selecciona'],
                        'format'=>'raw',
                    ],
                    [
                        'attribute' => 'id_estacion_actual',
                        'label' => 'Estacion',
                        'format' => 'raw',
                        'filter' => true,
                        'enableSorting' => false,
                        'value' => function ($model, $key, $index, $column) {
                            return $model->idEstacionActual->nombre;
                        },
                        'filterType'=> GridView::FILTER_SELECT2,
                        'filter'=> ArrayHelper::map(Estacion::find()->orderBy('nombre')->all(), 'id_estacion', 'nombre'),
                        'filterWidgetOptions'=>[
                            'pluginOptions'=>['allowClear'=>true],
                        ],
                        'filterInputOptions'=>['placeholder'=>'Selecciona'],
                    ], 
                    [
                        'attribute' => 'dias',
                        'format' => 'text',
                        'filter' => true,
                        'enableSorting' => false,
                    ],
                    [
                        'attribute' => 'estatus',
                        'label' => 'Estatus',
                        'format' => 'html',
                        'enableSorting' => true,
                        'filterType'=> GridView::FILTER_SELECT2,
                        'filter'=>ArrayHelper::map(EstadoServicio::find()->orderBy('nombre')->where('codigo = 12 OR codigo = 8')->all(), 'id', 'nombre'),
                        'filterWidgetOptions'=>[
                            'pluginOptions'=>['allowClear'=>true],
                        ],
                        'filterInputOptions'=>['placeholder'=>'Selecciona'],
                        'format'=>'raw',
                    ],
                    [  
                        'class' => 'yii\grid\ActionColumn',
                        //'contentOptions' => ['style' => 'width:260px;'],
                        'header'=>'Acciones',
                        'template' => '{view}',
                        'buttons' => [

                            //view button
                            'view' => function ($url, $model){
                                return Html::a('<span><i class="fa fa-eye fa-sm" aria-hidden="true"></i></span>',[ '/servicio/view', 'id' => $model->id, 'origen' => 1]);
                            },
                        ],

                   ],
                ],
            ]); ?>
        </div>
    </div>

</div>

<script>
    $('.table').removeClass( "table-bordered table-striped" );
</script>

views/servicio/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Servicio */

$this->title = 'Update Servicio: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Servicios', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="servicio-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'model_caso' => $model_caso,
    ]) ?>

</div>