models/SolicitudCompraPieza.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "solicitud_compra_pieza".
 *
 * @property integer $id
 * @property string $fecha
 * @property integer $codigo_estado
 * @property integer $id_servicio
 * @property integer $id_cotizacion_taller
 * @property integer $id_orden_trabajo
 *
 * @property PipelineCompraPieza[] $pipelineCompraPiezas
 * @property OrdenTrabajo $idOrdenTrabajo
 * @property SolicitudCompraProveedor[] $solicitudCompraProveedors
 */
class SolicitudCompraPieza extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'solicitud_compra_pieza';
    }

    /**
     * @inheritdoc
     */
    //$mlp = monto limite de pieza
    public $estado, $mlp;
    public function rules()
    {
        return [
            [['fecha'], 'safe'],
            [['codigo_estado', 'id_servicio', 'id_cotizacion_taller', 'id_orden_trabajo', 'estado', 'id_caso_estacion'], 'integer'],
            //[['id_orden_trabajo'], 'required'],
            [['mlp'], 'number'],
 
            [['observacion', 'observacion_recepcion', 'observacion_gerente', 'motivo_rechazo'], 'string'],
 
            [['id_orden_trabajo'], 'exist', 'skipOnError' => true, 'targetClass' => OrdenTrabajo::className(), 'targetAttribute' => ['id_orden_trabajo' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fecha' => 'Fecha',
            'codigo_estado' => 'Codigo Estado',
            'id_servicio' => 'Id Servicio',
            'id_cotizacion_taller' => 'Id Cotizacion Taller',
            'id_orden_trabajo' => 'Id Orden Trabajo',
            'observacion' => 'Observacion',
            'aprobacion' => 'Aprobacion',
            'observacion_recepcion' => 'Observacion Recepcion',
            'dias' => 'Días en Gestión',
            'observacion_gerente' => 'Observaciones',
            'motivo_rechazo' => 'Motivo de rechazo'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPipelineCompraPiezas()
    {
        return $this->hasMany(PipelineCompraPieza::className(), ['id_solicitud_compra_pieza' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdOrdenTrabajo()
    {
        return $this->hasOne(OrdenTrabajo::className(), ['id' => 'id_orden_trabajo']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSolicitudCompraProveedors()
    {
        return $this->hasMany(SolicitudCompraProveedor::className(), ['id_solicitud_compra_pieza' => 'id']);
    }

    public function getDias() {

        $connection = Yii::$app->getDb();
        $command = $connection->createCommand("
            (SELECT DATEDIFF(NOW(), s.fecha) as dias FROM solicitud_compra_pieza s WHERE s.id = ".$this->id.")");

        $result = $command->queryOne();

        return $result['dias'].' DÍAS';
    }
}

controllers/SolicitudCompraPiezaController.php
<?php

namespace app\controllers;

use Yii;
use app\models\SolicitudCompraPieza;
use app\models\SolicitudCompraPiezaSearch;
use app\models\Proveedor;
use app\models\SolicitudCompraProveedor;
use app\models\SolicitudCompraProveedorSearch;
use app\models\CotizacionProveedor;
use app\models\CotizacionProveedorPieza;
use app\models\CotizacionProveedorPiezaSearch;
use app\models\CotizacionTallerPieza;
use app\models\CotizacionTaller;
use app\models\OrdenCompraPieza;
use app\models\OrdenCompraPiezaSearch;
use app\models\OrdenCompraFactura;
use app\models\User;
use app\models\Flota;
use app\models\Servicio;
use app\models\Estacion;
use app\models\Vehiculo;
use app\models\EstadoCompraPieza;
use app\models\PipelineCompraPieza;
use app\models\DespachoSearch;
use app\models\Despacho;
use app\models\DespachoProveedorPiezaSearch;
use app\models\DespachoProveedorPieza;
use app\models\SolicitudServicioTaller;
use app\models\Taller;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use kartik\mpdf\Pdf;
use mPDF;
use app\models\EstadoServicio;
use app\models\PipelineServicio;
use app\models\MotivoDevolucion;
use app\models\SolicitudPiezaEstacion;
use app\models\UploadImagenPieza;
use yii\web\UploadedFile;
use app\models\Pieza;


/**
 * SolicitudCompraPiezaController implements the CRUD actions for SolicitudCompraPieza model.
 */

class SolicitudCompraPiezaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all SolicitudCompraPieza models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SolicitudCompraPiezaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->orderBy('id DESC');

        //Proveedor recomendado en base a la cantidad de ordenes de compras
        // $mejor_proveedor = OrdenCompraPieza::find()
        // ->select(['proveedor.nombre as pro, id_proveedor, COUNT(id_proveedor) totales'])
        // ->leftJoin('proveedor', '`proveedor`.`id` = `orden_compra_pieza`.`id_proveedor`')
        // ->groupBy(['id_proveedor'])
        // ->orderBy('totales DESC')
        // ->limit(3)
        // ->all();

        //Proveedor recomendado en base al porcentaje de descuento
        $mejor_proveedor = Proveedor::find()
        ->orderBy('porcentaje DESC')
        ->limit(3)
        ->all();


        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'mejor_proveedor' => $mejor_proveedor
        ]);
    }

    /**
     * Displays a single SolicitudCompraPieza model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new SolicitudCompraPieza model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new SolicitudCompraPieza();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing SolicitudCompraPieza model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing SolicitudCompraPieza model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the SolicitudCompraPieza model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return SolicitudCompraPieza the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = SolicitudCompraPieza::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

        /**
     * Solicitar cotizaciones a los talleres
     * @autor Zulma Hernández
     */
    public function actionSolicitudcotizacioninvitacion()
    {
        // print_r('entre');
        // die();
        if (Yii::$app->request->post()) {
            $id = Yii::$app->request->post('id');
            $model = $this->findModel($id);
            $proveedores = Yii::$app->request->post('proveedor');
            $enviadas = SolicitudCompraProveedor::find()->where(['id_solicitud_compra_pieza' => $model->id])->all();
            $cantidad_enviadas = count($enviadas);

            foreach ($proveedores as $i => $proveedor) {
                if ( $cantidad_enviadas > 0 ) {
                    foreach($enviadas as $env) {
                        if($env->id_proveedor == $proveedor) {
                            $band = 0;
                        }else {
                            $band = 1;
                        }
                    }
                } else{
                    $band = 1;
                }
                
                if($band == 1) {
                    $this->solicitudCompraProveedor($proveedor, $id);
                }else {
                    \Yii::$app->getSession()->setFlash('success', '¡La solicitud ha sido enviada con éxito!');
                }
            }
            if($cantidad_enviadas == 0) {               
                $model->codigo_estado = 1;
                if ($model->save()) {
                    $estado_compra_pieza = EstadoCompraPieza::findOne(['codigo' => 1])->id; //Espera de cotización
                    $model_pipeline_compra_pieza = new PipelineCompraPieza();
                    $model_pipeline_compra_pieza->fecha = date('Y-m-d');
                    $model_pipeline_compra_pieza->id_solicitud_compra_pieza = $model->id;
                    $model_pipeline_compra_pieza->id_estado_compra_pieza = $estado_compra_pieza;
                    $model_pipeline_compra_pieza->save();
                    unset($model_pipeline_compra_pieza);
                    \Yii::$app->getSession()->setFlash('success', '¡La solicitud se ha creado con éxito!');
                } else{
                    echo "No se pudo cambiar el estado de la solicitud";
                } 
            }else {
                \Yii::$app->getSession()->setFlash('success', '¡La solicitud ha sido enviada con éxito!');                
            }
        }
    }

    /**
     * Solicitar cotizaciones a los talleres
     * @autor Zulma Hernández
     */
    public function actionSolicitudcotizacion()
    {
        // print_r('entre');
        // die();
        if (Yii::$app->request->post()) {
            $id = Yii::$app->request->post('id');
            $model = $this->findModel($id);
            $proveedores = Yii::$app->request->post('proveedor');
            $enviadas = SolicitudCompraProveedor::find()->where(['id_solicitud_compra_pieza' => $model->id])->all();
            $cantidad_enviadas = count($enviadas);

            foreach ($proveedores as $i => $proveedor) {
                $this->solicitudCompraProveedor($proveedor, $id);
            }
            if($cantidad_enviadas == 0) {               
                $model->codigo_estado = 1;
                if ($model->save()) {
                    $estado_compra_pieza = EstadoCompraPieza::findOne(['codigo' => 1])->id; //Espera de cotización
                    $model_pipeline_compra_pieza = new PipelineCompraPieza();
                    $model_pipeline_compra_pieza->fecha = date('Y-m-d');
                    $model_pipeline_compra_pieza->id_solicitud_compra_pieza = $model->id;
                    $model_pipeline_compra_pieza->id_estado_compra_pieza = $estado_compra_pieza;
                    $model_pipeline_compra_pieza->save();
                    unset($model_pipeline_compra_pieza);
                    \Yii::$app->getSession()->setFlash('success', '¡La solicitud se ha creado con éxito!');
                } else{
                    echo "No se pudo cambiar el estado de la solicitud";
                } 
            }else {
                \Yii::$app->getSession()->setFlash('success', '¡La solicitud ha sido enviada con éxito!');                
            }
        }
    }

    protected function solicitudCompraProveedor($proveedor, $id)
    {
        $model = $this->findModel($id);
        $model_solicitud_compra_proveedor = new SolicitudCompraProveedor();
        $model_proveedor = Proveedor::findOne($proveedor);
        $model_solicitud_compra_proveedor->id_solicitud_compra_pieza = $model->id;
        $model_solicitud_compra_proveedor->id_proveedor = $model_proveedor->id;

        if ($model_solicitud_compra_proveedor->save(false)) {
            $model_cotizacion_proveedor = new CotizacionProveedor();
            $model_cotizacion_proveedor->fecha = date("Y-m-d H:i:s");

views/solicitud-compra-pieza/_expand-solicitud-aprobacion-pieza.php
<?php 
use yii\helpers\Html;
use kartik\select2\Select2;
use kartik\form\ActiveForm;

?>

<div class="expand-aprobacion-pieza">
	<div class="row">
		<div class="col-md-4 col-md-offset-1 col-xs-12">
			<div class="form-group">
                <label class="control-label" for="id_estado"><b>LISTADO DE PIEZAS</b></label>
                <?=  
                    Select2::widget([
                        'name' => 'id_pieza[]',
                        'data' => $piezas,
                        'options' => ['placeholder' => 'Selecciona la pieza', 'class' =>'id-pieza'],
                        'pluginOptions' => [ 'allowClear'=>true ],
                    ]); 
                ?>
            </div>
		</div>
		<div class="clearfix"></div>
		<div class="col-xs-10 col-xs-offset-1">
			<?php $form = ActiveForm::begin(['id' => 'aprobacion-form-'.$model->id, 'action' => ['solicitud-compra-pieza/aprobarsolicitud'] ] ); ?>
			<table class="table grid-blue table-responsive table-bordered">
				<thead>
					<tr>
						<th>Descripción</th>
						<th>Cantidad</th>
						<th>Proveedor</th>
						<th>Fecha entrega</th>
						<th>Costo</th>
						<th>Aprobar</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($cotizaciones_piezas as $i => $cotizacion): ?>
						<tr class="row-pieza" data-pieza="<?= $cotizacion->idCotizacionTallerPieza->id_pieza ?>">
							<td><?= ucfirst($cotizacion->idCotizacionTallerPieza->idPieza->nombre) ?></td>
							<td><?= $cotizacion->cantidad_comprar ?></td>
							<td><?= $cotizacion->idCotizacionProveedor->idSolicitudCompraProveedor->idProveedor->nombre ?></td>
							<td><?= date('d/m/Y', strtotime($cotizacion->fecha_entrega)) ?></td>
							<td><?= 'RD$ '.$cotizacion->costo ?> </td>
							<td><?= Html::checkbox('piezas[]', false, ['style' => 'display: block;margin-right: auto;margin-left: auto;', 'value' => $cotizacion->id, 'class' => 'cotizacion-pieza']); ?></td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
			<?php ActiveForm::end(); ?>
		</div>
	</div>
	</br>
	</br>
	<div class="row">
		<div class="col-xs-11">
			<div class="pull-right">
				<?= Html::a('Rechazar compra',[ '/solicitud-compra-pieza/index' ], ['class' => 'btn btn-cancelar']) ?>
				&nbsp;
				<?= Html::a('Aprobar compra','#', ['class' => 'btn btn-aceptar aprobar-compra', 'data' => ['id' => $model->id, ]]) ?>
			</div>
		</div>
	</div>
</div>
<style>
	.expand-aprobacion-pieza{
        padding: 10px 30px 20px 30px;
        text-align: left;
    }
</style>
<script>
	$('.id-pieza').on('change', function(event) {
		event.preventDefault();
		/* Act on the event */

		var id_pieza = $(this).val();
		$('tr.row-pieza').hide();
		if ( id_pieza == '') {
			$('.row-pieza').show();
		} else{
			$('tr[data-pieza='+id_pieza+']').show();
		}
	});
	$('.cotizacion-pieza').on('change', function(event) {
		event.preventDefault();
		/* Act on the event */
		var id_pieza = $(this).closest( "tr" ).data('pieza');

		if ( $(this).is(':checked') ) {
			$('tr[data-pieza='+id_pieza+'] .cotizacion-pieza').prop({
				disabled: true,
			});

			$(this).prop({
				disabled: false,
			});
		} else{
			$('tr[data-pieza='+id_pieza+'] .cotizacion-pieza').prop({
				disabled: false,
			});
		}
	});
	$('.aprobar-compra').on('click', function(event) {
		event.preventDefault();
        event.stopImmediatePropagation();

        var id = $(this).data('id');
        var form = $('#aprobacion-form-'+id);
        var data = form.serializeArray();
        data.push({name: 'id', value: id});

        $.post( form.attr("action"), data ).done(function(response){
            location.reload();
        });
	});
</script>

views/solicitud-compra-pieza/_modal_proveedor_recepcion.php
<!-- Modal Solciitar Cotizacion a Proveedores -->
<div id="solicitarCotizacionModal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="title"><img src="<?= Yii::$app->request->baseUrl ?>/img/give_money_64.png" alt="" style="height: 40px;">&nbsp;&nbsp; SOLICITUD DE COTIZACIÓN DE PIEZA</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times" aria-hidden="true" style="color: #000; font-weight: bold;"></i></button>
          </div>
        <div class="modal-body">
            </br>
            <?php $form = ActiveForm::begin([ 'id' => 'solicitar', 'action' => ['/solicitud-compra-pieza/solicitudcotizacion',] ]); ?>
                <div class="row">
                    <div class="col-xs-12 col-md-11 col-md-offset-1">
                        <label class="control-label" for="garantiavehiculo-motivo">PROVEEDORES</label>
                        <div id="response-proveedor" class="checkbox">
                        </div>
                    </div>
                </div>

            <?php ActiveForm::end(); ?>
            </br>
            <?php
            echo '<div class="row" style="padding-top: 25px;">';
                echo '<div class="text-center">';
                    echo Html::button('CANCELAR', ['class' => 'btn btn-cancelar', 'data' => ['dismiss' => 'modal']]);
                    echo "&nbsp;";
                    echo Html::submitButton('CONTINUAR', ['class' => 'btn btn-aceptar', 'form' => 'solicitar', 'id' => 'submit-solicitar' ]);
                echo '</div>';
            echo '</div>';
            ?>
        </div>
    </div>
  </div>
</div>
<!-- Fin modal-->

views/solicitud-compra-pieza/despacho.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use app\models\DespachoProveedorPieza;

$this->title = 'DESPACHAR PIEZAS';
?>

<div class="despacho">
	<div class="row">
		<div class="col-md-1 col-xs-3">
			<h4 class="titulo"><i class="fa fa-truck fa-4x" aria-hidden="true"></i></h4>
		</div>
		<div class="col-md-10 col-xs-9" style="padding-top: 20px;">
			<h4 class="titulo"><span> <?= Html::encode( $this->title ) ?></span></h4>
		</div>
	</div>
    </br>
    </br>
    <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
                <div class="pull-left">
                    <?php // Html::a('+ Nuevo Envío', '#', ['class' => 'btn btn-small-gris', 'data' => ['toggle' => 'modal', 'target' => '#alertAddEnvioBodegaModal']]) ?>
                    <?= Html::a('Listado de solicitudes', ['solicitud-compra-pieza/index', 'id' => $model->id ], ['class' => 'btn btn-small-gris',]) ?>
                </div>
                <div class="pull-right">
                    <?php // Html::a('+ Nuevo Envío', '#', ['class' => 'btn btn-small-gris', 'data' => ['toggle' => 'modal', 'target' => '#alertAddEnvioBodegaModal']]) ?>
                    <?= ($cantidad_piezas != $cantidad_piezas_despacho)? Html::a('+ Nuevo Envío', ['solicitud-compra-pieza/crearenvio', 'id' => $model->id ], ['class' => 'btn btn-small-verde',]): '' ?>
                </div>
        </div>
    </div>
    <div class="clearfix"></div>
    </br>
    <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'tableOptions' => ['class' => 'table table-responsive'],
                'summary' => '',
                'options' =>[
                    'class' => 'grid',
                ],
                'columns' => [
                    [
                        'attribute' => 'numero',
                        'label' => 'No. Envío',
                        'format' => 'text',
                        'contentOptions'=>['style'=>'text-align:center;'],
                        'filter' => false,
                        'enableSorting' => false,
                    ],
                    [
                        'attribute' => 'estado',
                        'label' => 'Estatus',
                        'format' => 'text',
                        'value' => function ($model) {
                            if ($model->estado == 0) {
                                return 'EN PROCESO';
                            } elseif ($model->estado == 1){
                                return 'ENVIADO A MENSAJERO';
                            } elseif ($model->estado == 2){
                                return 'RECIBIDA POR MENSAJERO';
                            } else {
                                return 'ENTREGADA';
                            }
                        },
                        'contentOptions'=>['style'=>'text-align:center;'],
                        'filter' => false,
                        'enableSorting' => false,
                    ],
                    [
                        'attribute' => 'fecha',
                        'label' => 'Fecha de Envío',
                        'format' => 'text',
                        'value' => function($model){
                            if ( $model->fecha )
                                return date( 'd/m/Y', strtotime($model->fecha) );
                            else
                                return '-';
                        },
                        'contentOptions'=>['style'=>'text-align:center;'],
                        'enableSorting' => false,
                    ],
                    [
                        'label' => 'No. de Piezas',
                        'format' => 'text',
                        'value' => function($model){
                            $cant = count(DespachoProveedorPieza::find()->where(['id_despacho' => $model->id])->all());
                            return $cant;
                        },
                        'contentOptions'=>['style'=>'text-align:center;'],
                        //'headerOptions' => ['width' => '300',],
                    ],
                    [
                        'attribute' => 'traslado',
                        'label' => 'Traslado',
                        'format' => 'text',
                        'value' => function($model){
                            if ( $model->traslado )
                                return $model->traslado;
                            else
                                return '-';
                        },
                        'contentOptions'=>['style'=>'text-align:center;'],
                        'enableSorting' => false,
                    ],
                    [
                        'attribute' => 'idMensajero.nombre',
                        'label' => 'Representante de Reparto',
                        'format' => 'text',
                        'value' => function($model){
                            if ( $model->id_mensajero )
                                return $model->idMensajero->nombre;
                            else
                                return '-';
                        },
                        'contentOptions'=>['style'=>'text-align:center;'],
                        'enableSorting' => false,
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'header' => 'Acciones',
                        'template' => '{update}',
                        'buttons' => [
                            'update' => function ($url, $model) {
                                return ($model->estado == 0 )?Html::a('<i class="fa fa-pencil" aria-hidden="true"></i>', ['/solicitud-compra-pieza/despachopiezas', 'id' => $model->id], ['title' => 'Editar Envío', ]):Html::a('<i class="fa fa-file" aria-hidden="true"></i>', ['/solicitud-compra-pieza/imprimirtranslado', 'id' => $model->id], ['title' => 'PDF Envío', ]);
                            },
                        ],
                        'contentOptions'=>['style'=>'text-align:center;'],
                    ],
                ],
            ]); ?>
        </div>
    </div>
</div>

<script>
    $('.table').removeClass( "table-bordered table-striped" );
</script>

views/solicitud-compra-pieza/solicitar-probacion.php
<?php
use yii\helpers\Html;
use kartik\form\ActiveForm;
use kartik\select2\Select2;

$this->title = 'SOLICITUD DE APROBACIÓN';

?>

<div class="solicitud-aprobacion">
	<div class="row">
        <div class="col-md-1 col-xs-3">
            <i class="fa fa-check fa-5x" aria-hidden="true"></i>
        </div>
        <div class="col-md-10 col-xs-9" style="padding-top: 10px;">
            <h4 class="titulo"><span> <?= Html::encode( $this->title ) ?></span></h4>
        </div>
    </div>
	</br>
	<div class="row">
		<div class="col-md-4 col-xs-12">
			<div class="form-group">
                <label class="control-label" for="id_estado">FILTRAR POR PIEZA</label>
                <?=  
                    Select2::widget([
                        'name' => 'id_pieza',
                        'data' => $piezas,
                        'options' => ['placeholder' => 'Selecciona la pieza', 'id' => 'id-pieza'],
                        'pluginOptions' => [ 'allowClear'=>true ],
                    ]); 
                ?>
            </div>
		</div>
        <div class="col-md-8 col-xs-12">
            <div class="pull-right" style="margin-top: 30px;">
                <?= Html::a('Listado de solicitudes',[ '/solicitud-compra-pieza/index' ], ['class' => 'btn btn-small-gris']) ?> 
            </div>
        </div>
    </div>
	</br>
	<?php $form = ActiveForm::begin(['id' => 'solicitud-aprobacion-form']); ?>
	<div class="row">
		<?php foreach ($cotizaciones_piezas as $key => $cotizacion): ?>
			<div class="col-md-6 col-xs-12">
				<div class="panel panel-default" data-pieza="<?= $cotizacion->idCotizacionTallerPieza->id_pieza ?>">
				  	<div class="panel-heading text-center" data-id="<?= $cotizacion->id ?>" >
				  		<b> <?= $cotizacion->idCotizacionProveedor->idSolicitudCompraProveedor->idProveedor->nombre ?> </b>
				  	</div>
		    		<table class="table table-bordered">
		    			<tbody>
		    				<tr>
		    					<td><b>Pieza: </b> <?= strtoupper($cotizacion->idCotizacionTallerPieza->idPieza->nombre) ?> </td>
		    				</tr>
		    				<tr>
		    					<td><b>Precio Final: </b> <?= ($cotizacion->costo)?'RD$ '.$cotizacion->costo:'<span class="sin-respuesta">SIN RESPUESTA</span>' ?> </td>
		    				</tr>
		    				<tr>
		    					<td><b>Fecha de entrega: </b> <?= ($cotizacion->fecha_entrega)?date('d/m/Y', strtotime($cotizacion->fecha_entrega)):'<span class="sin-respuesta">SIN RESPUESTA</span>' ?> </td>
		    				</tr>
		    			</tbody>
			    	</table>
				</div>
			</div>
		<?php endforeach ?>
	</div>
	</br>
	</br>
	</br>
	</br>
	<div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="form-group text-center">
                <?= Html::submitButton('Guardar', ['class' => 'btn btn-submit', 'id' => 'guardar-submit']) ?>
            </div>
        </div>
    </div>
	<?php ActiveForm::end(); ?>
	
</div>

<style>
	.panel{
		border-radius: 0px;
	}

	.panel .panel-heading{
		font-size: 12pt;
	}

	.sin-respuesta{
		color: #c51414;
		font-weight: bold;
	}

	.panel-heading {
	    padding: 5px 5px;
	}

	.panel-heading.selected {
		background-color: #c5e0b4;
	}

	.modal-dialog {
        margin: 80px auto;
    }
</style>
<script>
	$('#id-pieza').on('change', function(event) {
		event.preventDefault();
		/* Act on the event */
		var id_pieza = $(this).val();
		$('.panel').hide();
		if ( id_pieza == '') {
			$('.panel').show();
		} else{
			$('div[data-pieza='+id_pieza+']').show();
		}
	});
</script>